### PR TITLE
Fixed MorphOS support.

### PR DESCRIPTION
**Pull request by polluks**
Changed tooltype.

### CODE REVIEW

**Comment by sezero** [comment]
FYI:  .gitattributes file added by this commit results in a corrupted
fd2pragma.c upon cloning the repository.  Don't know why you added it
but I suggested removing it at https://github.com/adtools/fd2pragma/pull/6

**Comment by polluks** [comment]
@sezero Indeed? The attribute just changes a comment...

**Comment by polluks** [comment]
@sezero Indeed? The attribute just changes a comment...

**Comment by polluks** [comment]
@sezero Indeed? The attribute just changes a comment...

**Comment by polluks** [comment]
@sezero Indeed? The attribute just changes a comment...

**Comment by polluks** [comment]
@sezero Indeed? The attribute just changes a comment...

**Comment by sezero** [comment]
> @sezero Indeed? The attribute just changes a comment...

The code has string comparisons for "$Id" and the like and
the attribute messes them very badly for me. (Maybe it is my
old git-1.7.1 from centos6, don't know: just do a fresh clone
of the repo and do git diff)

**Comment by polluks** [comment]
I see, git 2.16.2.6 does not span multiple lines.

**Pull request merged**
